# 解析后文件格式：目前支持“excel”和“csv”（csv格式支持有待完善，尽量不要使用）
output_format: 'excel'

# 以下是各种银行格式配置，各字段顺序就是程序处理顺序，字段含义为：
#    amount_cols：需要转换成数字格式列的列表
#    cols：数据文件表头key
#    verify_cols：（v1版本）需要验证数据完整性的列，key为列名，value为true，验证key列是否存在空值
#    datetime_cols：需要转换成日期和时间格式列的列表，[0]是新日期列名称，[1]是带转换日期列
#                                                                                       [2]是新时间列名称，[3]是待转换时间列
#                                                                                       带转换日期列和时间列可以相同
#    merged_2cols：两列合并一列，key为新列名，value为需合并的两列名列表
#    split_col：分列，key为待分列名，value为列表，[0]为分割符，后面为新列名
#    copy_col：复制列，key为被复制列名，value为新列名
#    CDid：借贷标志，CD_col为借贷标志列，C为出账标记，C_col为出账列名，D为入账标记，D_col为入账列名，
#                                trans_col为交易金额列名
#    cols_new_order：解析后表头
#    col_name_map：将表头转换到标准列名的字典，key为现列名，value为标准列名
# 账户标准列名次序：['银行',姓名','证件号码','电话','地址','账号','卡号','余额',
#                                '开户日期','开户机构','账户状态', '销户日期','销户机构']
# 流水标准列名次序：['银行','日期','时间','姓名','账号','交易卡号','备注','摘要','币种','出账金额','入账金额','余额',
#                                '交易机构','资金来源','资金去向','对方户名','对方账号','对方开户行','对方证件号',
#                                'IP地址','MAC地址']
天津银行:
    账户:
        cols: ['所属银行','证件号码','开户名称','客户账号','卡号','余额','开户日期','开户机构名称','是否开通网易','U盾号','短信捆绑电话','网银电话','地址','邮编','销户日期','销户机构号','销户机构名称','账户状态']
        verify_cols:
            证件号码: true
            开户名称: true
        merged_2cols: 
            电话: ['短信捆绑电话','网银电话']
        cols_new_order: ['开户名称','证件号码','电话','地址','客户账号','卡号','余额','开户日期','开户机构名称','账户状态', '销户日期','销户机构名称','销户机构号','所属银行','是否开通网易','U盾号','邮编','短信捆绑电话','网银电话']
        col_name_map:
            开户名称: '姓名'
            客户账号: '账号'
            开户机构名称: '开户机构'
            销户机构名称: '销户机构'
    流水:
        amount_cols: ['交易金额','余额']
        cols: ['我行账号（卡号）','我方银行名称','我方中文名称','身份证号','交易日期','对方账号（卡号）','对方中文名称','对方银行名称','对方银行机构代码','流水号','借贷标志','交易金额','币种','余额','网银IP地址','交易代码（交易渠道）','代码描述','用途（摘要）','受理机构代码','受理机构名称','交易是否成功']
        verify_cols:
            我行账号（卡号）: true
            我方中文名称: true
            交易日期: true
            借贷标志: true
            交易金额: true
            余额: true
        datetime_cols: ['日期','交易日期','时间','交易日期']
        CDid:
            C: '借'
            D: '贷'
            CD_col: '借贷标志'
            C_col: '出账金额'
            D_col: '入账金额'
            trans_col: '交易金额'
        cols_new_order: ['日期','时间','我方中文名称', '我行账号（卡号）','用途（摘要）','币种','出账金额','入账金额','余额','受理机构名称','对方账号（卡号）','对方中文名称','对方银行名称','网银IP地址','我方银行名称','对方银行机构代码','受理机构代码','交易日期','借贷标志','交易金额','身份证号','流水号','交易代码（交易渠道）','代码描述','交易是否成功']
        col_name_map:
            我方中文名称: '姓名'
            我行账号（卡号）: '账号'
            用途（摘要）: '摘要'
            受理机构名称: '交易机构'
            对方中文名称: '对方户名'
            对方账号（卡号）: '对方账号'
            对方银行名称: '对方开户行'
            网银IP地址: 'IP地址'
            

    
