# 账户标准列名次序：['银行',姓名','证件号码','电话','地址','工作单位','账号','卡号','币种','余额',
#                                '开户日期','开户机构','上次交易日','账户状态','销户日期','销户机构']
# 流水标准列名次序：['银行','日期','时间','姓名','账号','卡号','备注','摘要','币种','出账金额','入账金额','余额',
#                                '交易机构','资金来源','资金去向','对方户名','对方账号','对方开户行','对方证件号',
#                                'IP地址','MAC地址']

# 解析后文件格式：目前支持“excel”和“csv”（csv格式支持有待完善，尽量不要使用）
output_format: 'excel'

# 各种数据表表头的hash值，可以用来判断该数据属于什么类型
header_hash:
    -7657799188243513271: ['天津银行','账户']
    8249071070838942687: ['天津银行','流水']
    8554201885240438826: ['建设银行网点','账户']
    -4544768075800427716: ['建设银行网点','流水']

# 以下是各种银行格式配置，账户信息和流水信息分别配置，冒号前为解析后字段名，冒号后可以为如下内容：
# 空值（null或无内容）：无操作
# 字符串（str）：该列（可以是新列）全部填充该字符串
# 布尔值（bool）：如为真则对该列进行数据检查，（v1）版本只检查空值
# 整数值（int）：该列解析为数值列，同时整数的真值也表示是否进行数据检查
# 子配置（dict）,子配置分为如下情况：
#           1. 配置项只有一个时，表示该列由原始列改名而来，子配置key为原列名，主配置key为新列名
#           2. 配置项大于一个时，表示该列为多个原始列合并而来，子配置key为原列名，主配置key为新列名
# 列表（list）,包含如下情况：
#           1. 格式转换二元组，[0]目标格式，[1]原始列，目标格式如下：
#                     1.1. date：原始列转换为日期格式后填充本配置列
#                     1.2. time：原始列转换为时间格式后填充本配置列
#           2. 借贷分列转换四元组，[0]为C（出账）或D（入账），[1]代表借贷标志列，
#                (也可使用fill实现)      [2]代表借或贷取值，[3]代表交易金额列
#           3. 条件填充四元组（fill），[1]填充标志列，[2]填充标志取值，[3]目标列
#           4. cols_new_order配置，解析后的列顺序
天津银行:
    账户: # ['所属银行','证件号码','开户名称','客户账号','卡号','余额','开户日期','开户机构名称','是否开通网易','U盾号','短信捆绑电话','网银电话','地址','邮编','销户日期','销户机构号','销户机构名称','账户状态']
        银行: 天津银行
        姓名: 
            开户名称: true
        证件号码: true
        电话: 
            短信捆绑电话: 
            网银电话: 
#         地址: 
#         工作单位: 
        账号: 
            客户账号: true
#         卡号: 
#         币种:
#         余额: 
#         开户日期: 
        开户机构: 
            开户机构名称: 
#         上次交易日: 
#         账户状态: 
#         销户日期: 
        销户机构: 
            销户机构名称: 
        cols_new_order: ['银行','姓名','证件号码','电话','地址','账号','卡号','余额','开户日期','开户机构','账户状态','销户日期','销户机构','销户机构号','所属银行','是否开通网易','U盾号','邮编','短信捆绑电话','网银电话']
    流水: # ['我行账号（卡号）','我方银行名称','我方中文名称','身份证号','交易日期','对方账号（卡号）','对方中文名称','对方银行名称','对方银行机构代码','流水号','借贷标志','交易金额','币种','余额','网银IP地址','交易代码（交易渠道）','代码描述','用途（摘要）','受理机构代码','受理机构名称','交易是否成功']
        银行: 天津银行
        日期: ['date','交易日期']
        时间: ['time','交易日期']
        姓名: 
            我方中文名称: true
        账号: 
            我行账号（卡号）: true
#         卡号: 
#         备注: 
        摘要: 
            用途（摘要）:
#         币种: 
        出账金额: ['C','借贷标志','借','交易金额']
        入账金额: ['D','借贷标志','贷','交易金额']
        余额: 100
        交易机构: 
            受理机构名称:
            我方银行名称:
#         资金来源: 
#         资金去向: 
        对方户名: 
            对方中文名称:
        对方账号: 
            对方账号（卡号）:
        对方开户行: 
            对方银行名称:
#         对方证件号:
        IP地址: 
            网银IP地址:
#         MAC地址:
        # 以下为需要特殊处理的原始列
        借贷标志: true
        交易金额: 100
        交易日期: true
        cols_new_order: ['银行','日期','时间','姓名','账号','摘要','币种','出账金额','入账金额','余额','交易机构','对方账号','对方户名','对方开户行','IP地址','我方银行名称','对方银行机构代码','受理机构代码','交易日期','借贷标志','交易金额','身份证号','流水号','交易代码（交易渠道）','代码描述','交易是否成功']
建设银行网点:        
    账户: # ['序号','账户名称','客户编号','证件类型','证件号码','账号','账户类型','借记卡主账户账号','币种','钞汇','册号','笔号','余额','可用余额','可冻结金额','开户日期','开户机构号','开户机构名称','开户柜员号','销户日期','销户机构号','销户机构名称','存款种类','上次交易日','账户状态','借记卡介质状态','借记卡挂失状态','移动电话','固定电话','居住地址','单位地址','户籍地址','工作单位','账户性质','资金用途','法人名称','法人证件类型','法人证件号码','结算账户分类代码','可售产品编号','可售产品名称']
        银行: 建设银行
        姓名: 
            账户名称: true
        证件号码: true
        电话: 
            移动电话: 
        地址: 
            居住地址:
            户籍地址:
#         工作单位: 
        账号: 
            借记卡主账户账号:
        卡号: 
            账号: true
#         币种:
#         余额: 
#         开户日期: 
        开户机构: 
            开户机构名称: 
#         上次交易日: 
#         账户状态: 
#         销户日期: 
        销户机构: 
            销户机构名称: 
        # 以下为需要特殊处理的原始列
        借记卡主账户账号: ['fill','借记卡主账户账号',~,'账号']
        cols_new_order: ['银行','姓名','证件号码','电话','地址','工作单位','账号','卡号','币种','余额','开户日期','开户机构','上次交易日','账户状态','销户日期','销户机构','可用余额','可冻结金额','账户性质','资金用途','账户类型','钞汇','存款种类','借记卡介质状态','借记卡挂失状态','固定电话','居住地址','单位地址','户籍地址','法人名称','法人证件类型','法人证件号码','结算账户分类代码','可售产品编号','可售产品名称','证件类型','客户编号','册号','笔号','开户机构号','开户柜员号','销户机构号']
    流水: # ['序号','客户名称','账号','币种','钞汇','册号','笔号','交易日期','交易时间','活期存款账户明细号','交易卡号','摘要','借贷方向','交易金额','账户余额','柜员号','交易机构号','交易机构名称','对方账号','对方户名','对方行名','交易流水号','交易渠道','自助设备编号','扩充备注','IP地址','MAC地址','第三方订单号','商户号','商户名称']
        银行: 建设银行
        日期: ['date','交易日期']
        时间: ['time','交易时间']
        姓名: 
            客户名称: true
#         账号: 
        卡号: 
            交易卡号: true
        备注: 
            扩充备注:
#         摘要: 
#         币种: 
        出账金额: ['C','借贷方向','借','交易金额']
        入账金额: ['D','借贷方向','贷','交易金额']
        余额:
            账户余额: 100
        交易机构: 
            交易机构名称:
#         资金来源: 
#         资金去向: 
#         对方户名: 
#         对方账号: 
        对方开户行: 
            对方行名:
#         对方证件号:
#         IP地址: 
#         MAC地址:
        # 以下为需要特殊处理的原始列
        借贷方向: true
        交易金额: 100
        交易日期: true
        交易时间: true
        cols_new_order: ['银行','日期','时间','姓名','卡号','备注','摘要','币种','出账金额','入账金额','余额','交易机构','对方户名','对方账号','对方开户行','IP地址','MAC地址','商户名称','商户号','交易流水号','第三方订单号','交易渠道','自助设备编号','账号','钞汇','册号','笔号','活期存款账户明细号','借贷方向','交易金额','柜员号','交易机构号']

